apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ncfn

resources:
  - namespace.yaml
  - pv-pvc.yaml
  - configmap-caddy.yaml
  - services.yaml
  - deployment-portal.yaml
  - deployment-caddy.yaml
  - deployment-cloudflared.yaml
  # secrets.yaml é gerado pelo migration.sh e aplicado separadamente
