tunnel: c1e9b8f1-5011-40fa-8840-b2212c02abc7
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: ncfn.net
    service: http://portal:3000
  - hostname: www.ncfn.net
    service: http://portal:3000
  - service: http_status:404
