tunnel: e0423fdb-84ac-4b6c-8a73-0fa4a5765c43
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: ncfn.net
    service: http://127.0.0.1:80
  - hostname: www.ncfn.net
    service: http://127.0.0.1:80
  - hostname: ncfn.ncfn.net
    service: http://127.0.0.1:3000
    originRequest:
      noTLSVerify: true
  - hostname: cloud.ncfn.net
    service: http://ncfn_nextcloud:80
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
  - service: http_status:404
